services:
  # Frontend Angular Service
  frontend:
    build:
      context: ./hospital-management
    image: abhi9701/hospital-frontend # <-- ADDED THIS LINE
    ports:
      - "4200:80"

  # API Gateway Service
  gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: ./gateway/requirements.txt
    image: abhi9701/hospital-gateway # <-- ADDED THIS LINE
    ports:
      - "5000:5000"
    command: python ./gateway/gateway.py
    volumes:
      - ./backend/instance:/app/instance
    env_file:
      - ./backend/.env

  # Appointment Service
  appointment_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: ./gateway/appointment_service/requirements.txt
    image: abhi9701/hospital-appointment-service # <-- ADDED THIS LINE
    command: python ./gateway/appointment_service/app.py
    volumes:
      - ./backend/instance:/app/instance
    env_file:
      - ./backend/.env

  # Doctor Service
  docter_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: ./gateway/docter_service/requirements.txt
    image: abhi9701/hospital-docter-service # <-- ADDED THIS LINE
    command: python ./gateway/docter_service/app.py
    volumes:
      - ./backend/instance:/app/instance
    env_file:
      - ./backend/.env

  # Auth Service
  auth_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: ./gateway/auth_service/requirements.txt
    image: abhi9701/hospital-auth-service # <-- ADDED THIS LINE
    command: python ./gateway/auth_service/app.py
    volumes:
      - ./backend/instance:/app/instance
    env_file:
      - ./backend/.env

  # Lab Service
  lab_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: ./gateway/lab_service/requirements.txt
    image: abhi9701/hospital-lab-service # <-- ADDED THIS LINE
    command: python ./gateway/lab_service/app.py
    volumes:
      - ./backend/instance:/app/instance
    env_file:
      - ./backend/.env
