version: "3.9"
services:
  frontend:
    build: ./hospital-management
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend/gateway
    ports:
      - "5000:5000"
