# This file defines the persistent storage for our database and our secret key.

# --- Persistent Volume Claim (PVC) ---
# This requests a small piece of storage (like a mini hard drive) from Kubernetes.
# We will attach this to our auth_service container to store the hospital.db file,
# ensuring the data persists even if the container restarts.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hospital-db-pvc
spec:
  accessModes:
    - ReadWriteOnce # This volume can be mounted by a single node
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage

---

# --- Secret ---
# This securely stores our SECRET_KEY environment variable.
# Instead of writing the key directly in our deployment files, we reference this Secret.
apiVersion: v1
kind: Secret
metadata:
  name: hospital-secret
type: Opaque
data:
  # The key must be base64 encoded. 
  # You can encode your key by running: echo -n 'your_super_secret_key' | base64
  # Replace the value below with the encoded version of your actual secret key.
  SECRET_KEY: 1ca1d3911bf1a31841e34f34f8b009f9ec7658a46cbc92ae26838e69bc306905

