# This file defines the Deployments and Services for our other backend microservices.

# --- Appointment Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: abhi9701/hospital-appointment-service:latest
          command: ["python"]
          args: ["gateway/appointment_service/app.py"]
          ports:
            - containerPort: 5002
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hospital-secret
                  key: SECRET_KEY
          # --- THIS IS THE FIX ---
          # Mount the shared database volume, just like in the auth-service.
          volumeMounts:
            - name: db-storage
              mountPath: /app/instance
      # Define the volume to be mounted.
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: hospital-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002

---

# --- Doctor Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docter-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docter-service
  template:
    metadata:
      labels:
        app: docter-service
    spec:
      containers:
        - name: docter-service
          image: abhi9701/hospital-docter-service:latest
          command: ["python"]
          args: ["gateway/docter_service/app.py"]
          ports:
            - containerPort: 5004
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hospital-secret
                  key: SECRET_KEY
          # --- THIS IS THE FIX ---
          # Mount the shared database volume.
          volumeMounts:
            - name: db-storage
              mountPath: /app/instance
      # Define the volume to be mounted.
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: hospital-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: docter-service
spec:
  selector:
    app: docter-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004

---

# --- Lab Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-service
  template:
    metadata:
      labels:
        app: lab-service
    spec:
      containers:
        - name: lab-service
          image: abhi9701/hospital-lab-service:latest
          command: ["python"]
          args: ["gateway/lab_service/app.py"]
          ports:
            - containerPort: 5003
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hospital-secret
                  key: SECRET_KEY
          # --- THIS IS THE FIX ---
          # Mount the shared database volume.
          volumeMounts:
            - name: db-storage
              mountPath: /app/instance
      # Define the volume to be mounted.
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: hospital-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec:
  selector:
    app: lab-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
