import { Component } from '@angular/core';
import { PrescriptionService } from '../services/prescription.service';
import jsPDF from 'jspdf';

@Component({
  selector: 'app-prescriptions',
  templateUrl: './prescriptions.component.html',
  styleUrls: ['./prescriptions.component.css']
})
export class PrescriptionsComponent {
  patientId = '';
  medicineName = '';
  dosage = '';
  timing = { morning: false, afternoon: false, night: false };

  medicines: any[] = [];
  searchResults: any[] = [];

  constructor(private prescriptionService: PrescriptionService) {}

  searchMedicine(query: string) {
    if (query.length < 2) return; // wait until 2+ chars
    this.prescriptionService.searchMedicines(query).subscribe(results => {
      this.searchResults = results;
    });
  }

  selectMedicine(med: any) {
    this.medicineName = med.name;
    this.searchResults = [];
  }

  addMedicine() {
    if (!this.medicineName || !this.dosage) return;
    const timingStr = Object.keys(this.timing)
      .filter(key => this.timing[key as keyof typeof this.timing])
      .join(', ');

    this.medicines.push({
      medicine_name: this.medicineName,
      dosage: this.dosage,
      timing: timingStr
    });

    this.medicineName = '';
    this.dosage = '';
    this.timing = { morning: false, afternoon: false, night: false };
  }

  removeMedicine(index: number) {
    this.medicines.splice(index, 1);
  }

  savePrescription() {
    this.prescriptionService.addPrescription({
      patient_id: Number(this.patientId),
      medicines: this.medicines
    }).subscribe(() => {
      alert("Prescription saved!");
      this.medicines = [];
      this.patientId = '';
    });
  }

  downloadPdf() {
  const doc = new jsPDF();

  // CarePlus Hospital heading
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 255); // Blue
  doc.text('CarePlus Hospital', 105, 20, { align: 'center' });

  // Prescription heading
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Prescription', 105, 35, { align: 'center' });

  // Patient info
  doc.setFontSize(12);
  doc.text(`Patient ID: ${this.patientId}`, 20, 50);

  // Medicines section heading
  doc.setFontSize(12);
  doc.setFont("helvetica", 'bold');
  doc.text('Medicines:', 20, 65);
  doc.setFont("helvetica", 'normal');

  // Medicines list
  let y = 75;
  this.medicines.forEach((m, idx) => {
    doc.text(
      `${idx + 1}. ${m.medicine_name} - Dosage: ${m.dosage} - Timing: ${m.timing}`,
      25,
      y
    );
    y += 10;

    // In case the list goes beyond the page height, add new page
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('Generated by CarePlus Hospital System', 105, 290, { align: 'center' });

  // Save
  doc.save(`prescription_${this.patientId}.pdf`);
}

}
